---
# tasks file for ansible-role-tshark

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create tshark_group
  group:
    name: "{{ tshark_group }}"
    state: present

- name: Create log directory
  file:
    path: "{{ tshark_log_dir }}"
    mode: 0775
    group: "{{ tshark_group }}"
    state: directory

- name: Add tshark_group_members to tshark_group
  user:
    name: "{{ item }}"
    groups: "{{ tshark_group }}"
    append: yes
  with_items: "{{ tshark_group_members }}"
